POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "firstName": "Adrian",
  "lastName": "Petcu",
  "email": "salam@salam.com",
  "role": "CUSTOMER",
  "password": "password"
}

###
